### ISSUE TITLE
Request to add a new LLM RecSys paper LlamaRec

### ISSUE THREAD

**Issue by Yueeeeeeee** [westlake-repl/Recommendation-Systems-without-Explicit-ID-Features-A-Literature-Review#2]
Hi,

Thank you for this awesome repo of Recsys without ID features, we recently release a workshop paper call LlamaRec, which uses text-based features for (re)ranking in two-stage recommendation. The paper can be found at https://arxiv.org/abs/2311.02089 and the code is available at: https://github.com/Yueeeeeeee/LlamaRec

Would you mind adding this work to your repo as well? Thank you!

**Comment by fajieyuan** [comment]
Pull a request

**Comment by Yueeeeeeee** [comment]
Submitted pull request:)

**Comment by fajieyuan** [comment]
sure

**Comment by fajieyuan** [comment]
solved
